version: '3'
services:
  nats:
    image: nats:latest
    ports:
    - 4222:4222 # for clients
    - 8222:8222 # an HTTP management port for information reporting
    - 6222:6222 # a routing port for clustering
  # cassandra:
  #   image: cassandra:latest
  #   volumes:
  #   - ./data/cassandra:/var/lib/cassandra
  postgres:
    image: postgres:latest
    ports:
    - 5432:5432
    # network_mode: host
    environment:
    - POSTGRES_USER=alextanhongpin
    - POSTGRES_PASSWORD=123456
    - POSTGRES_DB=grpc-openid
    volumes:
    - ./data/postgres:/var/lib/postgresql/data