// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth/auth.proto

/*
Package auth is a generated protocol buffer package.

It is generated from these files:
	auth/auth.proto

It has these top-level messages:
	AuthRequest
	AuthResponse
*/
package auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthRequest struct {
	Email    string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *AuthRequest) Reset()                    { *m = AuthRequest{} }
func (m *AuthRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()               {}
func (*AuthRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AuthRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthResponse struct {
	Error            string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	ErrorDescription string `protobuf:"bytes,2,opt,name=error_description,json=errorDescription" json:"error_description,omitempty"`
	AccessToken      string `protobuf:"bytes,3,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	Id               string `protobuf:"bytes,4,opt,name=id" json:"id,omitempty"`
}

func (m *AuthResponse) Reset()                    { *m = AuthResponse{} }
func (m *AuthResponse) String() string            { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()               {}
func (*AuthResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AuthResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *AuthResponse) GetErrorDescription() string {
	if m != nil {
		return m.ErrorDescription
	}
	return ""
}

func (m *AuthResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *AuthResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthRequest)(nil), "auth.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "auth.AuthResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AuthService service

type AuthServiceClient interface {
	Login(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	Register(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Login(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := grpc.Invoke(ctx, "/auth.AuthService/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Register(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := grpc.Invoke(ctx, "/auth.AuthService/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AuthService service

type AuthServiceServer interface {
	Login(context.Context, *AuthRequest) (*AuthResponse, error)
	Register(context.Context, *AuthRequest) (*AuthResponse, error)
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Register(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _AuthService_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/auth.proto",
}

func init() { proto.RegisterFile("auth/auth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0xd9, 0xd8, 0x96, 0xba, 0x2d, 0xd5, 0xac, 0x22, 0x31, 0xf4, 0xa0, 0x39, 0x49, 0x85,
	0x06, 0xf5, 0xd6, 0x8b, 0x28, 0x5e, 0x04, 0x41, 0x88, 0x9e, 0xbc, 0x94, 0x35, 0x19, 0xd2, 0xc5,
	0xb8, 0x1b, 0x77, 0x37, 0xf5, 0x2e, 0xbe, 0x81, 0x4f, 0xe1, 0xf3, 0xf8, 0x0a, 0x3e, 0x88, 0xec,
	0x6c, 0x89, 0x3d, 0xf6, 0xb2, 0xcc, 0x7c, 0xdf, 0xec, 0x8f, 0xf9, 0x43, 0x77, 0x78, 0x63, 0x17,
	0xa9, 0x7b, 0xa6, 0xb5, 0x56, 0x56, 0xb1, 0x8e, 0x8b, 0xe3, 0x71, 0xa9, 0x54, 0x59, 0x41, 0xca,
	0x6b, 0x91, 0x72, 0x29, 0x95, 0xe5, 0x56, 0x28, 0x69, 0x7c, 0x4d, 0x72, 0x49, 0x07, 0x57, 0x8d,
	0x5d, 0x64, 0xf0, 0xd6, 0x80, 0xb1, 0x6c, 0x9f, 0x76, 0xe1, 0x95, 0x8b, 0x2a, 0x22, 0x47, 0xe4,
	0x64, 0x3b, 0xf3, 0x09, 0x8b, 0x69, 0xbf, 0xe6, 0xc6, 0xbc, 0x2b, 0x5d, 0x44, 0x01, 0x1a, 0x6d,
	0x9e, 0x7c, 0x12, 0x3a, 0xf4, 0x04, 0x53, 0x2b, 0x69, 0x00, 0x11, 0x5a, 0x2b, 0xdd, 0x22, 0x5c,
	0xc2, 0x4e, 0x69, 0x88, 0xc1, 0xbc, 0x00, 0x93, 0x6b, 0x51, 0xbb, 0x1e, 0x56, 0xac, 0x5d, 0x34,
	0x6e, 0xfe, 0x75, 0x76, 0x4c, 0x87, 0x3c, 0xcf, 0xc1, 0x98, 0xb9, 0x55, 0x2f, 0x20, 0xa3, 0x2d,
	0xac, 0x1b, 0x78, 0xed, 0xd1, 0x49, 0x6c, 0x44, 0x03, 0x51, 0x44, 0x1d, 0x34, 0x02, 0x51, 0x9c,
	0x7f, 0x13, 0x3f, 0xc8, 0x03, 0xe8, 0xa5, 0xc8, 0x81, 0xdd, 0xd2, 0xee, 0x9d, 0x2a, 0x85, 0x64,
	0xe1, 0x14, 0x37, 0xb2, 0x36, 0x64, 0xcc, 0xd6, 0x25, 0xdf, 0x75, 0x72, 0xf8, 0xf1, 0xf3, 0xfb,
	0x15, 0xec, 0x25, 0xa3, 0x74, 0x79, 0x86, 0x3b, 0x4c, 0x2b, 0xf7, 0x7d, 0x46, 0x26, 0xec, 0x9e,
	0xf6, 0x33, 0x28, 0x85, 0xb1, 0xa0, 0x37, 0xa5, 0x8d, 0x91, 0x76, 0x90, 0x84, 0x2d, 0x4d, 0xaf,
	0x08, 0x33, 0x32, 0xb9, 0xee, 0x3d, 0xe1, 0x65, 0x9e, 0x7b, 0x78, 0x82, 0x8b, 0xbf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xfe, 0xe9, 0x88, 0x24, 0xb9, 0x01, 0x00, 0x00,
}
